<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('users', function (Blueprint $table) {
            $table->id();
            $table->foreignId('role_id')->constrained()->onDelete('restrict')->onUpdate('cascade');
            $table->foreignId('gender_id')->nullable()->constrained()->onDelete('restrict')->onUpdate('cascade');
            $table->string('firstname');
            $table->string('surname');
            $table->string('email')->unique()->nullable();
            $table->date('date_of_birth')->nullable();
            $table->string('street_number')->nullable();
            $table->string('zipcode')->nullable();
            $table->string('city')->nullable();
            $table->string('phone_number')->unique()->nullable();
            $table->integer('shirt_number')->nullable();
            $table->boolean('permission_photos');
            $table->boolean('active')->default(true);
            $table->timestamp('email_verified_at')->nullable();
            $table->string('password')->nullable();
            $table->rememberToken();
            $table->foreignId('current_team_id')->nullable();
            $table->string('profile_photo_path', 2048)->nullable();
            $table->timestamps();
        });

        DB::table('users')->insert(
            [
                [
                    'firstname' => 'Kobe',
                    'surname' => 'Schoeters',
                    'email' => 'r0889719@student.thomasmore.be',
                    'date_of_birth' => '1990-01-01',
                    'street_number' => 'Kleinhoefstraat 47',
                    'zipcode' => '2460',
                    'city' => 'Geel',
                    'phone_number' => '1234567890',
                    'shirt_number' => null,
                    'permission_photos' => true,
                    'active' => true,
                    'role_id' => 5, // Example role_id, adjust based on actual data
                    'gender_id' => 1, // Example gender_id, adjust based on actual data
                    'password' => Hash::make('admin1234'),
                    'profile_photo_path' => null,
                    'created_at' => now(),
                    'email_verified_at' => now()
                ],
                [
                    'firstname' => 'Jane',
                    'surname' => 'Doe',
                    'email' => 'jane.doe@mailinator.com',
                    'date_of_birth' => '1990-01-01',
                    'street_number' => 'Kleinhoefstraat 47',
                    'zipcode' => '2460',
                    'city' => 'Geel',
                    'phone_number' => '1234467890',
                    'shirt_number' => null,
                    'permission_photos' => true,
                    'active' => true,
                    'role_id' => 4,
                    'gender_id' => 2,
                    'password' => Hash::make('user1234'),
                    'profile_photo_path' => null,
                    'created_at' => now(),
                    'email_verified_at' => now()
                ],
                [
                    'firstname' => 'Lucas',
                    'surname' => 'Vermeulen',
                    'email' => 'lucas.vermeulen@mailinator.com',
                    'date_of_birth' => '1985-03-15',
                    'street_number' => 'Grote Markt 10',
                    'zipcode' => '1000',
                    'city' => 'Brussels',
                    'phone_number' => '0987654321',
                    'shirt_number' => null,
                    'permission_photos' => true,
                    'active' => true,
                    'role_id' => 4,
                    'gender_id' => 1,
                    'password' => Hash::make('pass1234'),
                    'profile_photo_path' => null,
                    'created_at' => now(),
                    'email_verified_at' => now()
                ],
                [
                    'firstname' => 'Sophie',
                    'surname' => 'Vandenberg',
                    'email' => 'sophie.vandenberg@mailinator.com',
                    'date_of_birth' => '1992-08-20',
                    'street_number' => 'Langestraat 112',
                    'zipcode' => '9000',
                    'city' => 'Ghent',
                    'phone_number' => '0123456789',
                    'shirt_number' => null,
                    'permission_photos' => true,
                    'active' => true,
                    'role_id' => 4,
                    'gender_id' => 2,
                    'password' => Hash::make('securepass'),
                    'profile_photo_path' => null,
                    'created_at' => now(),
                    'email_verified_at' => now()
                ],
                [
                    'firstname' => 'Pieter',
                    'surname' => 'Janssens',
                    'email' => 'pieter.janssens@mailinator.com',
                    'date_of_birth' => '1988-11-25',
                    'street_number' => 'Diestsestraat 235',
                    'zipcode' => '3000',
                    'city' => 'Leuven',
                    'phone_number' => '0470123456',
                    'shirt_number' => null,
                    'permission_photos' => true,
                    'active' => true,
                    'role_id' => 4,
                    'gender_id' => 1,
                    'password' => Hash::make('pieterpass'),
                    'profile_photo_path' => null,
                    'created_at' => now(),
                    'email_verified_at' => now()
                ],
                [
                    'firstname' => 'Eva',
                    'surname' => 'Peeters',
                    'email' => 'eva.peeters@mailinator.com',
                    'date_of_birth' => '1994-06-10',
                    'street_number' => 'Veldstraat 87',
                    'zipcode' => '9000',
                    'city' => 'Ghent',
                    'phone_number' => '0498775432',
                    'shirt_number' => null,
                    'permission_photos' => true,
                    'active' => true,
                    'role_id' => 4,
                    'gender_id' => 2,
                    'password' => Hash::make('evapass123'),
                    'profile_photo_path' => null,
                    'created_at' => now(),
                    'email_verified_at' => now()
                ],
                [
                    'firstname' => 'Bram',
                    'surname' => 'Maes',
                    'email' => 'bram.maes@mailinator.com',
                    'date_of_birth' => '1982-04-30',
                    'street_number' => 'Havermarkt 20',
                    'zipcode' => '3500',
                    'city' => 'Hasselt',
                    'phone_number' => '0365987412',
                    'shirt_number' => null,
                    'permission_photos' => true,
                    'active' => true,
                    'role_id' => 4,
                    'gender_id' => 1,
                    'password' => Hash::make('brampass456'),
                    'profile_photo_path' => null,
                    'created_at' => now(),
                    'email_verified_at' => now()
                ],
                [
                    'firstname' => 'Laura',
                    'surname' => 'Jacobs',
                    'email' => 'laura.jacobs@mailinator.com',
                    'date_of_birth' => '1987-09-18',
                    'street_number' => 'Meir 50',
                    'zipcode' => '2000',
                    'city' => 'Antwerp',
                    'phone_number' => '0345678901',
                    'shirt_number' => null,
                    'permission_photos' => true,
                    'active' => true,
                    'role_id' => 4,
                    'gender_id' => 2,
                    'password' => Hash::make('laurapass789'),
                    'profile_photo_path' => null,
                    'created_at' => now(),
                    'email_verified_at' => now()
                ],
                [
                    'firstname' => 'Stijn',
                    'surname' => 'Claes',
                    'email' => 'stijn.claes@mailinator.com',
                    'date_of_birth' => '1991-12-03',
                    'street_number' => 'Lombardenvest 2',
                    'zipcode' => '2000',
                    'city' => 'Antwerp',
                    'phone_number' => '0456789012',
                    'shirt_number' => null,
                    'permission_photos' => true,
                    'active' => true,
                    'role_id' => 4,
                    'gender_id' => 1,
                    'password' => Hash::make('stijnpass123'),
                    'profile_photo_path' => null,
                    'created_at' => now(),
                    'email_verified_at' => now()
                ],
                [
                    'firstname' => 'John',
                    'surname' => 'Doe',
                    'email' => 'john.doe@mailinator.com',
                    'date_of_birth' => '1976-11-1',
                    'street_number' => 'Kleinhoefstraat 47',
                    'zipcode' => '2460',
                    'city' => 'Geel',
                    'phone_number' => '1244567890',
                    'shirt_number' => null,
                    'permission_photos' => true,
                    'active' => true,
                    'role_id' => 1,
                    'gender_id' => 1,
                    'password' => Hash::make('user1234'),
                    'profile_photo_path' => null,
                    'created_at' => now(),
                    'email_verified_at' => now()
                ],
                [
                    'firstname' => 'Bob',
                    'surname' => 'Jones',
                    'email' => 'bob.jones@mailinator.com',
                    'date_of_birth' => '1980-11-12',
                    'street_number' => 'Molstraat 19',
                    'zipcode' => '2360',
                    'city' => 'Oud-Turnhout',
                    'phone_number' => '0493879008',
                    'shirt_number' => null,
                    'permission_photos' => true,
                    'active' => true,
                    'role_id' => 1,
                    'gender_id' => 1,
                    'password' => Hash::make('user1234'),
                    'profile_photo_path' => null,
                    'created_at' => now(),
                    'email_verified_at' => now()
                ],
                [
                    'firstname' => 'Wesley',
                    'surname' => 'Van Laer',
                    'email' => 'wesley.vl@mailinator.com',
                    'date_of_birth' => '2000-09-10',
                    'street_number' => 'Bergen Op Boom 20',
                    'zipcode' => '2300',
                    'city' => 'Turnhout',
                    'phone_number' => '0496547842',
                    'shirt_number' => null,
                    'permission_photos' => true,
                    'active' => true,
                    'role_id' => 1,
                    'gender_id' => 1,
                    'password' => Hash::make('user1234'),
                    'profile_photo_path' => null,
                    'created_at' => now(),
                    'email_verified_at' => now()
                ],
                [
                    'firstname' => 'Bobbie',
                    'surname' => 'Skoeters',
                    'email' => 'bobbie.skoeters@mailinator.com',
                    'date_of_birth' => '1980-11-12',
                    'street_number' => 'Molstraat 19',
                    'zipcode' => '2360',
                    'city' => 'Oud-Turnhout',
                    'phone_number' => '0493879098',
                    'shirt_number' => null,
                    'permission_photos' => true,
                    'active' => true,
                    'role_id' => 2,
                    'gender_id' => 1,
                    'password' => Hash::make('user1234'),
                    'profile_photo_path' => null,
                    'created_at' => now(),
                    'email_verified_at' => now()
                ],
                [
                    'firstname' => 'John',
                    'surname' => 'Smith',
                    'email' => 'john.smith@mailinator.com',
                    'date_of_birth' => '1985-05-25',
                    'street_number' => 'Kerkstraat 5',
                    'zipcode' => '1000',
                    'city' => 'Brussels',
                    'phone_number' => '0478901234',
                    'shirt_number' => null,
                    'permission_photos' => true,
                    'active' => true,
                    'role_id' => 2,
                    'gender_id' => 1,
                    'password' => Hash::make('pass1234'),
                    'profile_photo_path' => null,
                    'created_at' => now(),
                    'email_verified_at' => now()
                ],
                [
                    'firstname' => 'Emma',
                    'surname' => 'Johnson',
                    'email' => 'emma.johnson@mailinator.com',
                    'date_of_birth' => '1992-08-20',
                    'street_number' => 'Grote Markt 12',
                    'zipcode' => '9000',
                    'city' => 'Ghent',
                    'phone_number' => '0498765432',
                    'shirt_number' => null,
                    'permission_photos' => true,
                    'active' => true,
                    'role_id' => 2,
                    'gender_id' => 2,
                    'password' => Hash::make('securepass'),
                    'profile_photo_path' => null,
                    'created_at' => now(),
                    'email_verified_at' => now()
                ],
                [
                    'firstname' => 'Bert',
                    'surname' => 'Jansens',
                    'email' => null,
                    'date_of_birth' => '2010-12-7',
                    'street_number' => null,
                    'zipcode' => null,
                    'city' => null,
                    'phone_number' => null,
                    'shirt_number' => 44,
                    'permission_photos' => false,
                    'active' => true,
                    'role_id' => 3,
                    'gender_id' => 1,
                    'password' => Hash::make('user1234'),
                    'profile_photo_path' => '/storage/photos/test.jpg',
                    'created_at' => now(),
                    'email_verified_at' => now()
                ],
                [
                    'firstname' => 'Anna',
                    'surname' => 'Peters',
                    'email' => null,
                    'date_of_birth' => '2012-05-15',
                    'street_number' => null,
                    'zipcode' => null,
                    'city' => null,
                    'phone_number' => null,
                    'shirt_number' => 65,
                    'permission_photos' => false,
                    'active' => true,
                    'role_id' => 3,
                    'gender_id' => 2,
                    'password' => Hash::make('user1234'),
                    'profile_photo_path' => '/storage/photos/test.jpg',
                    'created_at' => now(),
                    'email_verified_at' => now()
                ],
                [
                    'firstname' => 'Lucas',
                    'surname' => 'Smits',
                    'email' => null,
                    'date_of_birth' => '2011-08-20',
                    'street_number' => null,
                    'zipcode' => null,
                    'city' => null,
                    'phone_number' => null,
                    'shirt_number' => 2,
                    'permission_photos' => false,
                    'active' => true,
                    'role_id' => 3,
                    'gender_id' => 1,
                    'password' => Hash::make('user1234'),
                    'profile_photo_path' => '/storage/photos/test.jpg',
                    'created_at' => now(),
                    'email_verified_at' => now()
                ],
                [
                    'firstname' => 'Emma',
                    'surname' => 'De Vries',
                    'email' => null,
                    'date_of_birth' => '2010-04-10',
                    'street_number' => null,
                    'zipcode' => null,
                    'city' => null,
                    'phone_number' => null,
                    'shirt_number' => 20,
                    'permission_photos' => false,
                    'active' => true,
                    'role_id' => 3,
                    'gender_id' => 2,
                    'password' => Hash::make('user1234'),
                    'profile_photo_path' => '/storage/photos/test.jpg',
                    'created_at' => now(),
                    'email_verified_at' => now()
                ],
                [
                    'firstname' => 'Noah',
                    'surname' => 'Bosman',
                    'email' => null,
                    'date_of_birth' => '2012-11-28',
                    'street_number' => null,
                    'zipcode' => null,
                    'city' => null,
                    'phone_number' => null,
                    'shirt_number' => 40,
                    'permission_photos' => false,
                    'active' => true,
                    'role_id' => 3,
                    'gender_id' => 1,
                    'password' => Hash::make('user1234'),
                    'profile_photo_path' => '/storage/photos/test.jpg',
                    'created_at' => now(),
                    'email_verified_at' => now()
                ],
                [
                    'firstname' => 'Eva',
                    'surname' => 'Bakker',
                    'email' => null,
                    'date_of_birth' => '2011-06-03',
                    'street_number' => null,
                    'zipcode' => null,
                    'city' => null,
                    'phone_number' => null,
                    'shirt_number' => 67,
                    'permission_photos' => false,
                    'active' => true,
                    'role_id' => 3,
                    'gender_id' => 2,
                    'password' => Hash::make('user1234'),
                    'profile_photo_path' => '/storage/photos/test.jpg',
                    'created_at' => now(),
                    'email_verified_at' => now()
                ],
                [
                    'firstname' => 'Liam',
                    'surname' => 'Verbeek',
                    'email' => null,
                    'date_of_birth' => '2010-09-19',
                    'street_number' => null,
                    'zipcode' => null,
                    'city' => null,
                    'phone_number' => null,
                    'shirt_number' => 87,
                    'permission_photos' => false,
                    'active' => true,
                    'role_id' => 3,
                    'gender_id' => 1,
                    'password' => Hash::make('user1234'),
                    'profile_photo_path' => '/storage/photos/test.jpg',
                    'created_at' => now(),
                    'email_verified_at' => now()
                ],
                [
                    'firstname' => 'Julia',
                    'surname' => 'Hendrickx',
                    'email' => null,
                    'date_of_birth' => '2012-03-25',
                    'street_number' => null,
                    'zipcode' => null,
                    'city' => null,
                    'phone_number' => null,
                    'shirt_number' => 98,
                    'permission_photos' => false,
                    'active' => true,
                    'role_id' => 3,
                    'gender_id' => 2,
                    'password' => Hash::make('user1234'),
                    'profile_photo_path' => '/storage/photos/test.jpg',
                    'created_at' => now(),
                    'email_verified_at' => now()
                ],
                [
                    'firstname' => 'Lando',
                    'surname' => 'Norris',
                    'email' => null,
                    'date_of_birth' => '2010-10-04',
                    'street_number' => null,
                    'zipcode' => null,
                    'city' => null,
                    'phone_number' => null,
                    'shirt_number' => 14,
                    'permission_photos' => false,
                    'active' => true,
                    'role_id' => 3,
                    'gender_id' => 1,
                    'password' => Hash::make('user1234'),
                    'profile_photo_path' => '/storage/photos/test.jpg',
                    'created_at' => now(),
                    'email_verified_at' => now()
                ],
                [
                    'firstname' => 'Lewis',
                    'surname' => 'Hamilton',
                    'email' => null,
                    'date_of_birth' => '2010-08-24',
                    'street_number' => null,
                    'zipcode' => null,
                    'city' => null,
                    'phone_number' => null,
                    'shirt_number' => 3,
                    'permission_photos' => false,
                    'active' => true,
                    'role_id' => 3,
                    'gender_id' => 1,
                    'password' => Hash::make('user1234'),
                    'profile_photo_path' => '/storage/photos/test.jpg',
                    'created_at' => now(),
                    'email_verified_at' => now()
                ],
            ]
        );
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('users');
    }
};
